In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading and cleaning both datasets

In [16]:
df_soccer = pd.read_csv('fifa_df.csv')
df_airplanes = pd.read_excel('EastWestAirlines.xlsx', sheet_name='data')

C:\Users\seboc\AppData\Local\Temp\ipykernel_25056\1499077156.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_soccer = pd.read_csv('fifa_df.csv')

## Cleaning Fifa Dataset

In [19]:
df_soccer.head()

,player_id,version,name,full_name,description,image,height_cm,weight_kg,dob,positions,...,composure,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,play_styles
0,231866,2025-06-03,Rodri -,Rodrigo Hernández Cascante,Rodri (born 22 June 1996) is a Spanish footbal...,https://cdn.sofifa.net/players/231/866/25_120.png,190,82,1996-06-22,"CDM,CM",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,209331,2025-06-03,Mohamed Salah Hamed Ghaly -,Mohamed Salah Hamed Ghalyمحمد صلاح,"Mohamed Salah (Mohamed Salah Hamed Ghaly, born...",https://cdn.sofifa.net/players/209/331/25_120.png,175,72,1992-06-15,"RM,RW",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,252371,2025-06-03,Jude Victor William Bellingham -,Jude Victor William Bellingham,Jude Bellingham (Jude Victor William Bellingha...,https://cdn.sofifa.net/players/252/371/25_120.png,186,75,2003-06-29,"CAM,CM",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,239085,2025-06-03,Erling Braut Håland -,Erling Braut Håland,"Erling Haaland (Erling Braut Håland, born 21 J...",https://cdn.sofifa.net/players/239/085/25_120.png,195,94,2000-07-21,ST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,238794,2025-06-03,Vini Jr. -,Vinicius José Paixão de Oliveira Junior,Vini Jr. (Vinicius José Paixão de Oliveira Jun...,https://cdn.sofifa.net/players/238/794/25_120.png,176,73,2000-07-12,"LW,ST",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_soccer.shape

(18205, 76)

In [21]:
df_soccer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18205 entries, 0 to 18204
Data columns (total 76 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player_id                  18205 non-null  int64
 1   version                    18205 non-null  object
 2   name                       18205 non-null  object
 3   full_name                  18205 non-null  object
 4   description                18205 non-null  object
 5   image                      18205 non-null  object
 6   height_cm                  18205 non-null  int64
 7   weight_kg                  18205 non-null  int64
 8   dob                        18205 non-null  object
 9   positions                  18205 non-null  object
 10  overall_rating             18205 non-null  int64
 11  potential                  18205 non-null  int64
 12  value                      18205 non-null  object
 13  wage                       18205 non-null  object
 14  preferred_foot             18205 non-null  object
 15  weak_foot                  18205 non-null  object
 16  skill_moves                18205 non-null  int64
 17  international_reputation   18205 non-null  object
 18  work_rate                  0 non-null      float64
 19  body_type                  18205 non-null  object
 20  real_face                  18205 non-null  object
 21  release_clause             16600 non-null  object
 22  specialities               915 non-null    object
 23  club_id                    18120 non-null  float64
 24  club_name                  18120 non-null  object
 25  club_league_id             18120 non-null  float64
 26  club_league_name           18120 non-null  object
 27  club_logo                  18120 non-null  object
 28  club_rating                18120 non-null  float64
 29  club_position              18120 non-null  object
 30  club_kit_number            18120 non-null  float64
 31  club_joined                18201 non-null  object
 32  club_contract_valid_until  18201 non-null  object
 33  country_id                 762 non-null    float64
 34  country_name               762 non-null    object
 35  country_league_id          762 non-null    object
 36  country_league_name        762 non-null    object
 37  country_flag               762 non-null    object
 38  country_rating             762 non-null    float64
 39  country_position           681 non-null    object
 40  country_kit_number         681 non-null    float64
 41  crossing                   0 non-null      float64
 42  finishing                  0 non-null      float64
 43  heading_accuracy           0 non-null      float64
 44  short_passing              0 non-null      float64
 45  volleys                    0 non-null      float64
 46  dribbling                  0 non-null      float64
 47  curve                      0 non-null      float64
 48  fk_accuracy                0 non-null      float64
 49  long_passing               0 non-null      float64
 50  ball_control               0 non-null      float64
 51  acceleration               0 non-null      float64
 52  sprint_speed               0 non-null      float64
 53  agility                    75 non-null     object
 54  reactions                  0 non-null      float64
 55  balance                    15265 non-null  object
 56  shot_power                 0 non-null      float64
 57  jumping                    0 non-null      float64
 58  stamina                    0 non-null      float64
 59  strength                   0 non-null      float64
 60  long_shots                 0 non-null      float64
 61  aggression                 0 non-null      float64
 62  interceptions              0 non-null      float64
 63  positioning                0 non-null      float64
 64  vision                     0 non-null      float64
 65  penalties                  0 non-null      float64
 66  composure                  0 non-null      float64
 67  defensive_awareness        0 non-null      float64
 68  standing_tackle            0 non-null      float64
 69  sliding_tackle             0 non-null      float64
 70  gk_diving                  0 non-null      float64
 71  gk_handling                0 non-null      float64
 72  gk_kicking                 0 non-null      float64
 73  gk_positioning             0 non-null      float64
 74  gk_reflexes                0 non-null      float64
 75  play_styles                0 non-null      float64
dtypes: float64(41), int64(6), object(29)
memory usage: 10.6+ MB

In [ ]:
# 1. DROP COLUMNS WITH 0 NON-NULL VALUES (completely empty)
empty_cols = [
    'work_rate', 'crossing', 'finishing', 'heading_accuracy', 'short_passing',
    'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control',
    'acceleration', 'sprint_speed', 'reactions', 'shot_power', 'jumping', 'stamina',
    'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision',
    'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle',
    'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles'
]
df_soccer.drop(columns=empty_cols, inplace=True)

In [25]:
df_soccer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18205 entries, 0 to 18204
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player_id                  18205 non-null  int64
 1   version                    18205 non-null  object
 2   name                       18205 non-null  object
 3   full_name                  18205 non-null  object
 4   description                18205 non-null  object
 5   image                      18205 non-null  object
 6   height_cm                  18205 non-null  int64
 7   weight_kg                  18205 non-null  int64
 8   dob                        18205 non-null  object
 9   positions                  18205 non-null  object
 10  overall_rating             18205 non-null  int64
 11  potential                  18205 non-null  int64
 12  value                      18205 non-null  object
 13  wage                       18205 non-null  object
 14  preferred_foot             18205 non-null  object
 15  weak_foot                  18205 non-null  object
 16  skill_moves                18205 non-null  int64
 17  international_reputation   18205 non-null  object
 18  body_type                  18205 non-null  object
 19  real_face                  18205 non-null  object
 20  release_clause             16600 non-null  object
 21  specialities               915 non-null    object
 22  club_id                    18120 non-null  float64
 23  club_name                  18120 non-null  object
 24  club_league_id             18120 non-null  float64
 25  club_league_name           18120 non-null  object
 26  club_logo                  18120 non-null  object
 27  club_rating                18120 non-null  float64
 28  club_position              18120 non-null  object
 29  club_kit_number            18120 non-null  float64
 30  club_joined                18201 non-null  object
 31  club_contract_valid_until  18201 non-null  object
 32  country_id                 762 non-null    float64
 33  country_name               762 non-null    object
 34  country_league_id          762 non-null    object
 35  country_league_name        762 non-null    object
 36  country_flag               762 non-null    object
 37  country_rating             762 non-null    float64
 38  country_position           681 non-null    object
 39  country_kit_number         681 non-null    float64
 40  agility                    75 non-null     object
 41  balance                    15265 non-null  object
dtypes: float64(7), int64(6), object(29)
memory usage: 5.8+ MB

In [ ]:
# 2. DROP COLUMNS WITH VERY LOW NON-NULL COUNT 
low_data_cols = [
    'specialities', 
    'country_id', 'country_name', 'country_league_id', 'country_league_name',
    'country_flag', 'country_rating', 'country_position', 'country_kit_number',  # ~4%
    'agility'  
]
df_soccer.drop(columns=low_data_cols, inplace=True)

In [29]:
df_soccer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18205 entries, 0 to 18204
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player_id                  18205 non-null  int64
 1   version                    18205 non-null  object
 2   name                       18205 non-null  object
 3   full_name                  18205 non-null  object
 4   description                18205 non-null  object
 5   image                      18205 non-null  object
 6   height_cm                  18205 non-null  int64
 7   weight_kg                  18205 non-null  int64
 8   dob                        18205 non-null  object
 9   positions                  18205 non-null  object
 10  overall_rating             18205 non-null  int64
 11  potential                  18205 non-null  int64
 12  value                      18205 non-null  object
 13  wage                       18205 non-null  object
 14  preferred_foot             18205 non-null  object
 15  weak_foot                  18205 non-null  object
 16  skill_moves                18205 non-null  int64
 17  international_reputation   18205 non-null  object
 18  body_type                  18205 non-null  object
 19  real_face                  18205 non-null  object
 20  release_clause             16600 non-null  object
 21  club_id                    18120 non-null  float64
 22  club_name                  18120 non-null  object
 23  club_league_id             18120 non-null  float64
 24  club_league_name           18120 non-null  object
 25  club_logo                  18120 non-null  object
 26  club_rating                18120 non-null  float64
 27  club_position              18120 non-null  object
 28  club_kit_number            18120 non-null  float64
 29  club_joined                18201 non-null  object
 30  club_contract_valid_until  18201 non-null  object
 31  balance                    15265 non-null  object
dtypes: float64(4), int64(6), object(22)
memory usage: 4.4+ MB

In [28]:
df_soccer.head()

,player_id,version,name,full_name,description,image,height_cm,weight_kg,dob,positions,...,club_name,club_league_id,club_league_name,club_logo,club_rating,club_position,club_kit_number,club_joined,club_contract_valid_until,balance
0,231866,2025-06-03,Rodri -,Rodrigo Hernández Cascante,Rodri (born 22 June 1996) is a Spanish footbal...,https://cdn.sofifa.net/players/231/866/25_120.png,190,82,1996-06-22,"CDM,CM",...,Manchester City,13.0,Premier League,https://cdn.sofifa.net/meta/team/9/30.png,85.0,RES,16.0,2019-07-04,2027,d
1,209331,2025-06-03,Mohamed Salah Hamed Ghaly -,Mohamed Salah Hamed Ghalyمحمد صلاح,"Mohamed Salah (Mohamed Salah Hamed Ghaly, born...",https://cdn.sofifa.net/players/209/331/25_120.png,175,72,1992-06-15,"RM,RW",...,Liverpool,13.0,Premier League,https://cdn.sofifa.net/meta/team/8/30.png,84.0,RM,11.0,2017-07-01,2027,dAttack
2,252371,2025-06-03,Jude Victor William Bellingham -,Jude Victor William Bellingham,Jude Bellingham (Jude Victor William Bellingha...,https://cdn.sofifa.net/players/252/371/25_120.png,186,75,2003-06-29,"CAM,CM",...,Real Madrid,53.0,La Liga,https://cdn.sofifa.net/meta/team/3468/30.png,85.0,RCM,5.0,2023-07-01,2029,Build-UpdRoaming
3,239085,2025-06-03,Erling Braut Håland -,Erling Braut Håland,"Erling Haaland (Erling Braut Håland, born 21 J...",https://cdn.sofifa.net/players/239/085/25_120.png,195,94,2000-07-21,ST,...,Manchester City,13.0,Premier League,https://cdn.sofifa.net/meta/team/9/30.png,85.0,SUB,9.0,2022-07-01,2034,NaN
4,238794,2025-06-03,Vini Jr. -,Vinicius José Paixão de Oliveira Junior,Vini Jr. (Vinicius José Paixão de Oliveira Jun...,https://cdn.sofifa.net/players/238/794/25_120.png,176,73,2000-07-12,"LW,ST",...,Real Madrid,53.0,La Liga,https://cdn.sofifa.net/meta/team/3468/30.png,85.0,LW,7.0,2018-07-12,2027,AttackdRoaming

In [33]:
unique_positions = df_soccer['positions'].str.split(',').explode().str.strip().unique()
print(unique_positions)

['CDM' 'CM' 'RM' 'RW' 'CAM' 'ST' 'LW' 'CB' 'GK' 'LM' 'RB' 'LB' 'LDM']

## Cleaning Airplane Dataset

In [18]:
df_airplanes.head(10)

,ID#,Balance,Qual_miles,cc1_miles,cc2_miles,cc3_miles,Bonus_miles,Bonus_trans,Flight_miles_12mo,Flight_trans_12,Days_since_enroll,Award?
0,1,28143,0,1,1,1,174,1,0,0,7000,0
1,2,19244,0,1,1,1,215,2,0,0,6968,0
2,3,41354,0,1,1,1,4123,4,0,0,7034,0
3,4,14776,0,1,1,1,500,1,0,0,6952,0
4,5,97752,0,4,1,1,43300,26,2077,4,6935,1
5,6,16420,0,1,1,1,0,0,0,0,6942,0
6,7,84914,0,3,1,1,27482,25,0,0,6994,0
7,8,20856,0,1,1,1,5250,4,250,1,6938,1
8,9,443003,0,3,2,1,1753,43,3850,12,6948,1
9,10,104860,0,3,1,1,28426,28,1150,3,6931,1